language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database DBCoverflow_test' -U postgres